# [[language]]
# name = "c"
# language-server = { command = "ccls" }
# indent = { tab-width = 2, unit = "\t" }

# [[language]]
# name = "cpp"
# language-server = { command = "ccls" }
# indent = { tab-width = 2, unit = "\t" }

# [[language]]
# name = "rust"
# language-server = { command = "rustup", args = ["run", "nightly", "rust-analyzer"] }

[[language]]
name = "ruby"
language-server = { command = "solargraph" }
indent = { tab-width = 2, unit = "\t" }
config = { solargraph = { diagnostics = true, formatting = true } }
comment-token = "#"
shebangs = ["ruby", "rb", "crystal", "cr"]
file-types = ["rb", "cr"]

[[language]]
name = "elixir"
language-server = { command = "~/.config/elixir-ls/language_server.sh" }
# config = { solargraph = { diagnostics = true, formatting = true } }
indent = { tab-width = 2, unit = "\t" }

[[language]]
name = "javascript"
shebangs = ["deno", "node"]
roots = ["deno.json", "package.json", "tsconfig.json"]
config = { enable = true, lint = true, unstable = true }
language-server = { command = "deno", args = ["lsp"], language-id = "javascript" }

[[language]]
name = "jsx"
shebangs = ["deno", "node"]
roots = ["deno.json", "package.json", "tsconfig.json"]
config = { enable = true, lint = true, unstable = true }
language-server = { command = "deno", args = ["lsp"], language-id = "javascriptreact" }

[[language]]
name = "typescript"
shebangs = ["deno", "node"]
roots = ["deno.json", "package.json", "tsconfig.json"]
config = { enable = true, lint = true, unstable = true }
language-server = { command = "deno", args = ["lsp"], language-id = "typescript" }

[[language]]
name = "tsx"
shebangs = ["deno", "node"]
roots = ["deno.json", "package.json", "tsconfig.json"]
config = { enable = true, lint = true, unstable = true }
language-server = { command = "deno", args = ["lsp"], language-id = "typescriptreact" }
